#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'


  DIReserved = %w|
    { } ; name base ddir wfc port termport
    record multiplex_level no ld id aps stacksize linkage ld db_group *
    sysdata space bd type redirect redirect_port priority log
  |

class DIParser < Racc::Parser

module_eval(<<'...end DIparser.y/module_eval...', 'DIparser.y', 184)

  def initialize
    @yydebug = true
  end

  def parse_file(f)
    @f = f
    @line_no = 0
    @line = ""
    do_parse
  end

  def next_token
    loop do
      @line = fetch_line(@line)
      unless @line
        return [false, :END_OF_FILE]
      end

      token = case @line
      when /\A\s+/
        nil
      when /\A\d+/
        [:INTEGER,$&.to_i]
      when %r!\A"(.*?)"!
        s = $1
        [:STRING,s]
      when %r!\A\w+!
        s = $&
        DIReserved.index(s) ? [s,s] : [:NAME,s]
      when /\A./
        s=$&
        [s,s]
      end
      
      @line = $'
      return token if token
    end
  end

  def on_error(t,val,vstack)
    raise ParseError, "\nunexpected token #{t} #{val.inspect} #{vstack}"
  end

  def fetch_line(line)
    if line.empty?
      line=@f.gets
      @line_no += 1 if line
    end
    line
  end

...end DIparser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    76,     6,     7,    57,    57,    15,    41,    18,    20,    22,
    54,    54,    42,    47,    10,    50,    14,    34,    35,    36,
    37,     1,   123,     4,   124,    78,    43,    81,    82,    83,
    74,    75,     6,     7,    44,    47,    15,    50,    18,    20,
    22,    67,    69,    67,    69,    10,    45,    14,    46,    40,
    31,    53,     1,    38,     4,    61,    62,    63,    64,    31,
    70,    71,    28,    73,    27,    84,    26,    86,    87,    25,
    89,    90,    91,    92,    93,    94,    95,    96,    97,    98,
    99,   100,   101,   105,   106,   110,   111,   112,   113,   114,
   115,   116,   117,   118,   119,   120,   105,   122,    24,   126,
   106,   128,   129,   130,   131 ]

racc_action_check = [
    53,     0,     0,    56,    32,     0,    20,     0,     0,     0,
    56,    32,    22,    28,     0,    28,     0,    14,    14,    14,
    14,     0,   106,     0,   106,    53,    24,    53,    53,    53,
    53,    53,    17,    17,    25,    49,    17,    49,    17,    17,
    17,    42,    42,    66,    66,    17,    26,    17,    27,    18,
    29,    31,    17,    15,    17,    33,    38,    40,    41,    12,
    47,    48,    10,    50,     9,    54,     7,    57,    65,     4,
    67,    69,    70,    71,    73,    74,    75,    76,    77,    78,
    81,    82,    83,    84,    86,    87,    89,    90,    94,    95,
    96,    97,    99,   100,   101,   102,   103,   105,     1,   107,
   108,   120,   124,   125,   126 ]

racc_action_pointer = [
    -1,    75,   nil,   nil,    65,   nil,   nil,    62,   nil,    64,
    51,   nil,    32,   nil,    -1,    46,   nil,    30,    42,   nil,
    -1,   nil,     1,   nil,    21,    29,    41,    48,    -1,    23,
   nil,    40,   -15,    50,   nil,   nil,   nil,   nil,    51,   nil,
    52,    53,    28,   nil,   nil,   nil,   nil,    53,    49,    21,
    56,   nil,   nil,    -3,    54,   nil,   -16,    56,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    56,    30,    63,   nil,    64,
    67,    68,   nil,    69,    52,    53,    70,    66,    50,   nil,
   nil,    73,    74,    75,    76,   nil,    80,    80,   nil,    81,
    82,   nil,   nil,   nil,    83,    84,    85,    86,   nil,    87,
    88,    89,    83,    89,   nil,    92,    -1,    87,    96,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    96,   nil,   nil,   nil,    79,    98,    99,   nil,   nil,   nil,
   nil,   nil ]

racc_action_default = [
    -2,   -76,    -9,   -10,   -76,   -11,    -7,   -76,   -12,   -76,
   -76,   -13,   -61,   -14,   -76,   -76,   -15,    -3,   -76,    -4,
   -76,    -6,   -76,    -8,   -76,   -76,   -76,   -76,   -34,   -62,
   -63,   -76,   -16,   -76,   -41,   -42,   -43,   -44,   -76,    -5,
   -76,   -76,   -27,   -45,   -46,   -22,   132,   -76,   -76,   -35,
   -76,   -36,   -64,   -66,   -76,    -1,   -17,   -76,   -18,   -20,
   -21,   -40,   -23,   -24,   -25,   -76,   -28,   -76,   -29,   -76,
   -76,   -76,   -37,   -76,   -76,   -76,   -76,   -76,   -76,   -67,
   -68,   -76,   -76,   -76,   -56,   -19,   -48,   -76,   -30,   -76,
   -76,   -38,   -33,   -39,   -76,   -76,   -76,   -76,   -69,   -76,
   -76,   -76,   -76,   -57,   -58,   -76,   -76,   -76,   -49,   -50,
   -26,   -31,   -32,   -73,   -74,   -75,   -65,   -70,   -71,   -72,
   -76,   -59,   -60,   -54,   -76,   -76,   -76,   -51,   -55,   -53,
   -52,   -47 ]

racc_goto_table = [
    58,    68,    51,   104,   109,     9,    65,    66,    17,    48,
    30,    19,    49,    56,    33,   107,   108,    55,   125,   102,
   103,    32,   121,    72,    85,    88,   127,    52,    39,    29,
    12,    77,    79,    80 ]

racc_goto_check = [
    17,    22,    25,    33,    29,     1,    20,    21,     5,    23,
    35,     6,    24,    16,    26,    27,    28,     4,    30,    31,
    32,     3,    33,    25,    17,    22,    29,    35,     6,    34,
     2,    36,    37,    38 ]

racc_goto_pointer = [
   nil,     5,    30,     9,   -15,     8,    11,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -19,   -32,   nil,   nil,
   -36,   -35,   -41,   -19,   -16,   -26,     0,   -71,   -70,   -82,
   -88,   -65,   -64,   -81,    17,    -2,   -22,   -21,   -20 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,    23,     2,
     3,     5,     8,    11,    13,    16,   nil,   nil,    59,    60,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 36, :_reduce_1,
  0, 37, :_reduce_2,
  1, 37, :_reduce_none,
  1, 40, :_reduce_4,
  2, 40, :_reduce_5,
  1, 41, :_reduce_6,
  1, 41, :_reduce_7,
  1, 41, :_reduce_8,
  1, 41, :_reduce_9,
  1, 41, :_reduce_10,
  1, 41, :_reduce_11,
  1, 41, :_reduce_12,
  1, 41, :_reduce_13,
  1, 41, :_reduce_14,
  1, 41, :_reduce_15,
  0, 39, :_reduce_16,
  1, 39, :_reduce_17,
  1, 51, :_reduce_18,
  2, 51, :_reduce_19,
  1, 52, :_reduce_20,
  1, 52, :_reduce_21,
  3, 42, :_reduce_22,
  3, 43, :_reduce_23,
  3, 44, :_reduce_24,
  3, 45, :_reduce_25,
  5, 50, :_reduce_26,
  0, 55, :_reduce_27,
  1, 55, :_reduce_28,
  1, 56, :_reduce_29,
  2, 56, :_reduce_30,
  3, 57, :_reduce_31,
  3, 57, :_reduce_32,
  5, 49, :_reduce_33,
  0, 58, :_reduce_34,
  1, 58, :_reduce_35,
  1, 59, :_reduce_36,
  2, 59, :_reduce_37,
  3, 60, :_reduce_38,
  3, 60, :_reduce_39,
  3, 46, :_reduce_40,
  1, 61, :_reduce_41,
  1, 61, :_reduce_42,
  1, 61, :_reduce_43,
  1, 61, :_reduce_44,
  3, 47, :_reduce_45,
  3, 48, :_reduce_46,
  5, 54, :_reduce_47,
  0, 62, :_reduce_48,
  1, 62, :_reduce_49,
  1, 63, :_reduce_50,
  2, 63, :_reduce_51,
  3, 64, :_reduce_52,
  2, 65, :_reduce_53,
  1, 65, :_reduce_54,
  5, 53, :_reduce_55,
  0, 66, :_reduce_56,
  1, 66, :_reduce_57,
  1, 67, :_reduce_58,
  2, 67, :_reduce_59,
  2, 68, :_reduce_60,
  0, 38, :_reduce_61,
  1, 38, :_reduce_none,
  1, 69, :_reduce_63,
  2, 69, :_reduce_64,
  5, 70, :_reduce_65,
  0, 71, :_reduce_66,
  1, 71, :_reduce_none,
  1, 72, :_reduce_68,
  2, 72, :_reduce_69,
  3, 73, :_reduce_70,
  3, 73, :_reduce_71,
  3, 73, :_reduce_72,
  3, 73, :_reduce_73,
  3, 73, :_reduce_74,
  3, 73, :_reduce_75 ]

racc_reduce_n = 76

racc_shift_n = 132

racc_token_table = {
  false => 0,
  :error => 1,
  :directory_sengen => 2,
  "name" => 3,
  :NAME => 4,
  ";" => 5,
  "base" => 6,
  :STRING => 7,
  "ddir" => 8,
  "record" => 9,
  "sysdata" => 10,
  "{" => 11,
  "}" => 12,
  "space" => 13,
  "port" => 14,
  "wfc" => 15,
  "term_port" => 16,
  "multiplex_level" => 17,
  "no" => 18,
  "ld" => 19,
  "id" => 20,
  "aps" => 21,
  "stacksize" => 22,
  :INTEGER => 23,
  "linkage" => 24,
  "*" => 25,
  "bd" => 26,
  "db_group" => 27,
  :db_group_teigi_list => 28,
  :db_gourp_teigi => 29,
  "type" => 30,
  "redirect" => 31,
  "redirect_port" => 32,
  "priority" => 33,
  "log" => 34 }

racc_nt_base = 35

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "directory_sengen",
  "\"name\"",
  "NAME",
  "\";\"",
  "\"base\"",
  "STRING",
  "\"ddir\"",
  "\"record\"",
  "\"sysdata\"",
  "\"{\"",
  "\"}\"",
  "\"space\"",
  "\"port\"",
  "\"wfc\"",
  "\"term_port\"",
  "\"multiplex_level\"",
  "\"no\"",
  "\"ld\"",
  "\"id\"",
  "\"aps\"",
  "\"stacksize\"",
  "INTEGER",
  "\"linkage\"",
  "\"*\"",
  "\"bd\"",
  "\"db_group\"",
  "db_group_teigi_list",
  "db_gourp_teigi",
  "\"type\"",
  "\"redirect\"",
  "\"redirect_port\"",
  "\"priority\"",
  "\"log\"",
  "$start",
  "system_teigitai",
  "teigi1_list_opt",
  "db_group_list_opt",
  "teigi2_list_opt",
  "teigi1_list",
  "teigi1",
  "system_mei_teigi",
  "base_sengen",
  "ddir_sengen",
  "record_sengen",
  "multiplex_level_sitei",
  "gamen_stack_sengen",
  "system_kyotu_ryoiki_sengen",
  "wfc_sengen",
  "sysdata_sengen",
  "teigi2_list",
  "teigi2",
  "batch_sengen",
  "ld_sengen",
  "sysdata_teigi_list_opt",
  "sysdata_teigi_list",
  "sysdata_teigi",
  "wfc_teigi_list_opt",
  "wfc_teigi_list",
  "wfc_teigi",
  "tajuuka_level",
  "ld_teigi_list_opt",
  "ld_teigi_list",
  "ld_teigi",
  "aps_kijutu",
  "batch_teigi_list_opt",
  "batch_teigi_list",
  "batch_teigi",
  "db_group_list",
  "db_group",
  "db_group_teigi_list_opt",
  "db_gourp_teigi_list",
  "db_group_teigi" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'DIparser.y', 14)
  def _reduce_1(val, _values)
          val[0].merge! val[2]
      val[0][:db_groups] = val[1]
      val[0]
    
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 20)
  def _reduce_2(val, _values)
    {}
  end
.,.,

# reduce 3 omitted

module_eval(<<'.,.,', 'DIparser.y', 24)
  def _reduce_4(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 25)
  def _reduce_5(val, _values)
    val[0].merge! val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 28)
  def _reduce_6(val, _values)
    {:name=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 29)
  def _reduce_7(val, _values)
    {:dirs=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 30)
  def _reduce_8(val, _values)
    {:base=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 31)
  def _reduce_9(val, _values)
    {:ddir=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 32)
  def _reduce_10(val, _values)
    {:record=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 33)
  def _reduce_11(val, _values)
    {:multiplex_level=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 34)
  def _reduce_12(val, _values)
    {:screen_stack_size=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 35)
  def _reduce_13(val, _values)
    {:linkage=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 36)
  def _reduce_14(val, _values)
    {:wfc=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 37)
  def _reduce_15(val, _values)
    {:sysdata=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 40)
  def _reduce_16(val, _values)
    {}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 41)
  def _reduce_17(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 45)
  def _reduce_18(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 46)
  def _reduce_19(val, _values)
    val[0].merge! val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 49)
  def _reduce_20(val, _values)
    {:batchs=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 50)
  def _reduce_21(val, _values)
    {:lds=>val[0]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 55)
  def _reduce_22(val, _values)
          val[1]
    
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 59)
  def _reduce_23(val, _values)
    val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 62)
  def _reduce_24(val, _values)
    val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 65)
  def _reduce_25(val, _values)
    val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 68)
  def _reduce_26(val, _values)
     val[2] 
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 71)
  def _reduce_27(val, _values)
    {}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 72)
  def _reduce_28(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 75)
  def _reduce_29(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 76)
  def _reduce_30(val, _values)
    val[0].merge! val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 79)
  def _reduce_31(val, _values)
    {:space=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 80)
  def _reduce_32(val, _values)
    {:port=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 83)
  def _reduce_33(val, _values)
     val[2] 
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 86)
  def _reduce_34(val, _values)
    {}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 87)
  def _reduce_35(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 90)
  def _reduce_36(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 91)
  def _reduce_37(val, _values)
    val[0].merge! val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 94)
  def _reduce_38(val, _values)
    {:port=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 95)
  def _reduce_39(val, _values)
    {:termport=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 98)
  def _reduce_40(val, _values)
     val[1] 
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 101)
  def _reduce_41(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 102)
  def _reduce_42(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 103)
  def _reduce_43(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 104)
  def _reduce_44(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 107)
  def _reduce_45(val, _values)
     val[1] 
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 110)
  def _reduce_46(val, _values)
     val[1] 
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 113)
  def _reduce_47(val, _values)
     val[2] 
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 116)
  def _reduce_48(val, _values)
    []
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 117)
  def _reduce_49(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 120)
  def _reduce_50(val, _values)
    val
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 121)
  def _reduce_51(val, _values)
    val[0]<<val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 124)
  def _reduce_52(val, _values)
    {:name=>val[0],:launch_opt=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 127)
  def _reduce_53(val, _values)
    val.join("")
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 128)
  def _reduce_54(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 131)
  def _reduce_55(val, _values)
    val[2]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 134)
  def _reduce_56(val, _values)
    []
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 135)
  def _reduce_57(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 138)
  def _reduce_58(val, _values)
    val
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 139)
  def _reduce_59(val, _values)
    val[0]<<val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 142)
  def _reduce_60(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 145)
  def _reduce_61(val, _values)
    []
  end
.,.,

# reduce 62 omitted

module_eval(<<'.,.,', 'DIparser.y', 149)
  def _reduce_63(val, _values)
    [val[2]]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 150)
  def _reduce_64(val, _values)
    val[0] << val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 153)
  def _reduce_65(val, _values)
    [val[2]]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 156)
  def _reduce_66(val, _values)
    {}
  end
.,.,

# reduce 67 omitted

module_eval(<<'.,.,', 'DIparser.y', 160)
  def _reduce_68(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 161)
  def _reduce_69(val, _values)
    val[0].merge! val[1]
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 164)
  def _reduce_70(val, _values)
    {:type=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 165)
  def _reduce_71(val, _values)
    {:redirect_to=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 166)
  def _reduce_72(val, _values)
    {:redirect_port=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 167)
  def _reduce_73(val, _values)
    {:priority=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 168)
  def _reduce_74(val, _values)
    {:log=>val[1]}
  end
.,.,

module_eval(<<'.,.,', 'DIparser.y', 169)
  def _reduce_75(val, _values)
    {:name=>val[1]}
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class DIParser



if $0 == __FILE__
  parser = DIParser.new
  p parser.parse_file(ARGF)
end
